name: Metrics
on:
 schedule: # execute every 12 hours
    - cron: "* */12 * * *"

 workflow_dispatch:

 push:
    branches:
    - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.details.svg?layout=compact&theme=gotham
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, Objective-C, Ruby, Starlark, Handlebars, tex, less, makefile, qmake, lex, cmake,
            gnuplot, TSX
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
